-- City catalog (40 agencies). Idempotent by slug.
-- Removes demo agencies created per city. Does not create fake reviews.

delete from agencies
where slug in (
  'inmobiliaria-sol-madrid',
  'gestion-urbana-madrid',
  'pisos-barcelona',
  'inmobiliaria-javier-valencia',
  'fincas-mediterraneo-malaga',
  'gestion-inmobiliaria-central-sevilla'
);

insert into agencies (
  slug, name, address, city, postal_code, phone, phone_published, email, website,
  claimed, verified, premium
)
select
  v.slug,
  v.name,
  v.address,
  v.city,
  v.postal_code,
  '',
  false,
  '',
  v.website,
  false,
  false,
  false
from (
  values
  ('tecnocasa-barcelona', 'Tecnocasa', 'Oficina en Barcelona', 'Barcelona', '08001', 'https://www.tecnocasa.es'),
  ('donpiso-barcelona', 'donpiso', 'Oficina en Barcelona', 'Barcelona', '08001', 'https://www.donpiso.com'),
  ('engel-volkers-barcelona', 'Engel & Völkers', 'Oficina en Barcelona', 'Barcelona', '08001', 'https://www.engelvoelkers.com'),
  ('look-find-barcelona', 'Look & Find', 'Oficina en Barcelona', 'Barcelona', '08001', 'https://www.lookandfind.es'),
  ('lucas-fox-barcelona', 'Lucas Fox', 'Oficina en Barcelona', 'Barcelona', '08001', 'https://www.lucasfox.com'),
  ('aproperties-barcelona', 'Aproperties', 'Oficina en Barcelona', 'Barcelona', '08001', 'https://www.aproperties.es'),
  ('housfy-barcelona', 'Housfy', 'Oficina en Barcelona', 'Barcelona', '08001', 'https://housfy.com'),
  ('forcadell-barcelona', 'Forcadell', 'Oficina en Barcelona', 'Barcelona', '08001', 'https://www.forcadell.com'),
  ('alquiler-seguro-barcelona', 'Alquiler Seguro', 'Oficina en Barcelona', 'Barcelona', '08001', 'https://www.alquilerseguro.es'),
  ('vivendex-barcelona', 'Vivendex', 'Oficina en Barcelona', 'Barcelona', '08001', 'https://www.vivendex.com'),
  ('tecnocasa-valencia', 'Tecnocasa', 'Oficina en Valencia', 'Valencia', '46001', 'https://www.tecnocasa.es'),
  ('donpiso-valencia', 'donpiso', 'Oficina en Valencia', 'Valencia', '46001', 'https://www.donpiso.com'),
  ('engel-volkers-valencia', 'Engel & Völkers', 'Oficina en Valencia', 'Valencia', '46001', 'https://www.engelvoelkers.com'),
  ('look-find-valencia', 'Look & Find', 'Oficina en Valencia', 'Valencia', '46001', 'https://www.lookandfind.es'),
  ('re-max-valencia', 'RE/MAX', 'Oficina en Valencia', 'Valencia', '46001', 'https://www.remax.es'),
  ('century-21-valencia', 'Century 21', 'Oficina en Valencia', 'Valencia', '46001', 'https://www.century21.es'),
  ('alquiler-seguro-valencia', 'Alquiler Seguro', 'Oficina en Valencia', 'Valencia', '46001', 'https://www.alquilerseguro.es'),
  ('housfy-valencia', 'Housfy', 'Oficina en Valencia', 'Valencia', '46001', 'https://housfy.com'),
  ('alfa-inmobiliaria-valencia', 'Alfa Inmobiliaria', 'Oficina en Valencia', 'Valencia', '46001', 'https://www.alfainmo.com'),
  ('redpiso-valencia', 'Redpiso', 'Oficina en Valencia', 'Valencia', '46001', 'https://www.redpiso.es'),
  ('tecnocasa-malaga', 'Tecnocasa', 'Oficina en Málaga', 'Málaga', '29001', 'https://www.tecnocasa.es'),
  ('engel-volkers-malaga', 'Engel & Völkers', 'Oficina en Málaga', 'Málaga', '29001', 'https://www.engelvoelkers.com'),
  ('donpiso-malaga', 'donpiso', 'Oficina en Málaga', 'Málaga', '29001', 'https://www.donpiso.com'),
  ('look-find-malaga', 'Look & Find', 'Oficina en Málaga', 'Málaga', '29001', 'https://www.lookandfind.es'),
  ('re-max-malaga', 'RE/MAX', 'Oficina en Málaga', 'Málaga', '29001', 'https://www.remax.es'),
  ('gilmar-malaga', 'Gilmar', 'Oficina en Málaga', 'Málaga', '29001', 'https://www.gilmar.es'),
  ('lucas-fox-malaga', 'Lucas Fox', 'Oficina en Málaga', 'Málaga', '29001', 'https://www.lucasfox.com'),
  ('alquiler-seguro-malaga', 'Alquiler Seguro', 'Oficina en Málaga', 'Málaga', '29001', 'https://www.alquilerseguro.es'),
  ('century-21-malaga', 'Century 21', 'Oficina en Málaga', 'Málaga', '29001', 'https://www.century21.es'),
  ('iad-espana-malaga', 'iad España', 'Oficina en Málaga', 'Málaga', '29001', 'https://www.iadspain.es'),
  ('tecnocasa-sevilla', 'Tecnocasa', 'Oficina en Sevilla', 'Sevilla', '41001', 'https://www.tecnocasa.es'),
  ('donpiso-sevilla', 'donpiso', 'Oficina en Sevilla', 'Sevilla', '41001', 'https://www.donpiso.com'),
  ('engel-volkers-sevilla', 'Engel & Völkers', 'Oficina en Sevilla', 'Sevilla', '41001', 'https://www.engelvoelkers.com'),
  ('look-find-sevilla', 'Look & Find', 'Oficina en Sevilla', 'Sevilla', '41001', 'https://www.lookandfind.es'),
  ('re-max-sevilla', 'RE/MAX', 'Oficina en Sevilla', 'Sevilla', '41001', 'https://www.remax.es'),
  ('alquiler-seguro-sevilla', 'Alquiler Seguro', 'Oficina en Sevilla', 'Sevilla', '41001', 'https://www.alquilerseguro.es'),
  ('century-21-sevilla', 'Century 21', 'Oficina en Sevilla', 'Sevilla', '41001', 'https://www.century21.es'),
  ('alfa-inmobiliaria-sevilla', 'Alfa Inmobiliaria', 'Oficina en Sevilla', 'Sevilla', '41001', 'https://www.alfainmo.com'),
  ('redpiso-sevilla', 'Redpiso', 'Oficina en Sevilla', 'Sevilla', '41001', 'https://www.redpiso.es'),
  ('housfy-sevilla', 'Housfy', 'Oficina en Sevilla', 'Sevilla', '41001', 'https://housfy.com')
) as v(slug, name, address, city, postal_code, website)
on conflict (slug) do update set
  name = excluded.name,
  address = excluded.address,
  city = excluded.city,
  postal_code = excluded.postal_code,
  website = excluded.website;

insert into agency_name_aliases (agency_id, alias, kind)
select a.id, v.alias, 'commercial'
from (
  values
  ('tecnocasa-barcelona', 'Grupo Tecnocasa'),
  ('tecnocasa-barcelona', 'Tecnocasa Barcelona'),
  ('tecnocasa-barcelona', 'Tecnocasa España'),
  ('donpiso-barcelona', 'Don Piso'),
  ('donpiso-barcelona', 'Donpiso Barcelona'),
  ('donpiso-barcelona', 'donpiso Barcelona'),
  ('engel-volkers-barcelona', 'Engel and Volkers'),
  ('engel-volkers-barcelona', 'Engel Voelkers'),
  ('engel-volkers-barcelona', 'Engel & Volkers Barcelona'),
  ('engel-volkers-barcelona', 'E&V'),
  ('look-find-barcelona', 'Look and Find'),
  ('look-find-barcelona', 'Look&Find'),
  ('look-find-barcelona', 'Look & Find Barcelona'),
  ('lucas-fox-barcelona', 'Lucas Fox Barcelona'),
  ('lucas-fox-barcelona', 'LucasFox'),
  ('aproperties-barcelona', 'A Properties'),
  ('aproperties-barcelona', 'Aproperties Barcelona'),
  ('housfy-barcelona', 'Housfy Alquiler'),
  ('housfy-barcelona', 'Housfy Barcelona'),
  ('forcadell-barcelona', 'Forcadell Barcelona'),
  ('forcadell-barcelona', 'Inmobiliaria Forcadell'),
  ('alquiler-seguro-barcelona', 'AlquilerSeguro'),
  ('alquiler-seguro-barcelona', 'Alquiler Seguro S.A.'),
  ('alquiler-seguro-barcelona', 'Alquiler Seguro Barcelona'),
  ('vivendex-barcelona', 'Vivendex Barcelona'),
  ('vivendex-barcelona', 'Inmobiliaria Vivendex'),
  ('tecnocasa-valencia', 'Grupo Tecnocasa'),
  ('tecnocasa-valencia', 'Tecnocasa Valencia'),
  ('tecnocasa-valencia', 'Tecnocasa España'),
  ('donpiso-valencia', 'Don Piso'),
  ('donpiso-valencia', 'Donpiso Valencia'),
  ('donpiso-valencia', 'donpiso Valencia'),
  ('engel-volkers-valencia', 'Engel and Volkers'),
  ('engel-volkers-valencia', 'Engel Voelkers'),
  ('engel-volkers-valencia', 'Engel & Volkers Valencia'),
  ('engel-volkers-valencia', 'E&V'),
  ('look-find-valencia', 'Look and Find'),
  ('look-find-valencia', 'Look&Find'),
  ('look-find-valencia', 'Look & Find Valencia'),
  ('re-max-valencia', 'Remax'),
  ('re-max-valencia', 'REMAX'),
  ('re-max-valencia', 'RE/MAX Valencia'),
  ('century-21-valencia', 'Century21'),
  ('century-21-valencia', 'C21'),
  ('century-21-valencia', 'Century 21 Valencia'),
  ('alquiler-seguro-valencia', 'AlquilerSeguro'),
  ('alquiler-seguro-valencia', 'Alquiler Seguro Valencia'),
  ('housfy-valencia', 'Housfy Alquiler'),
  ('housfy-valencia', 'Housfy Valencia'),
  ('alfa-inmobiliaria-valencia', 'Alfa Inmo'),
  ('alfa-inmobiliaria-valencia', 'Alfa Inmobiliaria Valencia'),
  ('redpiso-valencia', 'Red Piso'),
  ('redpiso-valencia', 'Redpiso Valencia'),
  ('tecnocasa-malaga', 'Grupo Tecnocasa'),
  ('tecnocasa-malaga', 'Tecnocasa Málaga'),
  ('tecnocasa-malaga', 'Tecnocasa Malaga'),
  ('engel-volkers-malaga', 'Engel and Volkers'),
  ('engel-volkers-malaga', 'Engel Voelkers'),
  ('engel-volkers-malaga', 'Engel & Volkers Málaga'),
  ('engel-volkers-malaga', 'E&V'),
  ('donpiso-malaga', 'Don Piso'),
  ('donpiso-malaga', 'Donpiso Málaga'),
  ('donpiso-malaga', 'donpiso Malaga'),
  ('look-find-malaga', 'Look and Find'),
  ('look-find-malaga', 'Look&Find'),
  ('look-find-malaga', 'Look & Find Málaga'),
  ('re-max-malaga', 'Remax'),
  ('re-max-malaga', 'REMAX'),
  ('re-max-malaga', 'RE/MAX Málaga'),
  ('re-max-malaga', 'RE/MAX Malaga'),
  ('gilmar-malaga', 'Gilmar Málaga'),
  ('gilmar-malaga', 'Gilmar Marbella'),
  ('gilmar-malaga', 'Inmobiliaria Gilmar'),
  ('lucas-fox-malaga', 'Lucas Fox Málaga'),
  ('lucas-fox-malaga', 'Lucas Fox Marbella'),
  ('lucas-fox-malaga', 'LucasFox'),
  ('alquiler-seguro-malaga', 'AlquilerSeguro'),
  ('alquiler-seguro-malaga', 'Alquiler Seguro Málaga'),
  ('century-21-malaga', 'Century21'),
  ('century-21-malaga', 'C21'),
  ('century-21-malaga', 'Century 21 Málaga'),
  ('iad-espana-malaga', 'iad'),
  ('iad-espana-malaga', 'IAD'),
  ('iad-espana-malaga', 'iad Spain'),
  ('iad-espana-malaga', 'iad Málaga'),
  ('tecnocasa-sevilla', 'Grupo Tecnocasa'),
  ('tecnocasa-sevilla', 'Tecnocasa Sevilla'),
  ('tecnocasa-sevilla', 'Tecnocasa España'),
  ('donpiso-sevilla', 'Don Piso'),
  ('donpiso-sevilla', 'Donpiso Sevilla'),
  ('donpiso-sevilla', 'donpiso Sevilla'),
  ('engel-volkers-sevilla', 'Engel and Volkers'),
  ('engel-volkers-sevilla', 'Engel Voelkers'),
  ('engel-volkers-sevilla', 'Engel & Volkers Sevilla'),
  ('engel-volkers-sevilla', 'E&V'),
  ('look-find-sevilla', 'Look and Find'),
  ('look-find-sevilla', 'Look&Find'),
  ('look-find-sevilla', 'Look & Find Sevilla'),
  ('re-max-sevilla', 'Remax'),
  ('re-max-sevilla', 'REMAX'),
  ('re-max-sevilla', 'RE/MAX Sevilla'),
  ('alquiler-seguro-sevilla', 'AlquilerSeguro'),
  ('alquiler-seguro-sevilla', 'Alquiler Seguro Sevilla'),
  ('century-21-sevilla', 'Century21'),
  ('century-21-sevilla', 'C21'),
  ('century-21-sevilla', 'Century 21 Sevilla'),
  ('alfa-inmobiliaria-sevilla', 'Alfa Inmo'),
  ('alfa-inmobiliaria-sevilla', 'Alfa Inmobiliaria Sevilla'),
  ('redpiso-sevilla', 'Red Piso'),
  ('redpiso-sevilla', 'Redpiso Sevilla'),
  ('housfy-sevilla', 'Housfy Alquiler'),
  ('housfy-sevilla', 'Housfy Sevilla')
) as v(slug, alias)
join agencies a on a.slug = v.slug
where not exists (
  select 1
  from agency_name_aliases existing
  where existing.agency_id = a.id
    and lower(existing.alias) = lower(v.alias)
);
